# ZEITRISS Markdownlint-Konfiguration
# Fokus: Zeilenlänge <= 100 Zeichen, Frontmatter und Tabellen bleiben unangetastet.
default: true
MD003:
  style: atx
MD007:
  indent: 2
MD009:
  br_spaces: 2
MD013:
  line_length: 100
  heading_line_length: 120
  code_block_line_length: 120
  tables: false
  strict: false
MD022:
  lines_above: 1
  lines_below: 1
MD024:
  allow_different_nesting: true
MD025:
  front_matter_title: ""
MD026:
  punctuation: ".:;!"
MD029:
  style: ordered
MD033: false
MD034: false
MD036: false
MD041:
  level: 1
  front_matter_title: ""
